/** @type {import('tailwindcss').Config} */
const config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#e4e2dd",
        "secondary-container": "#fed488",
        "inverse-primary": "#c8c6c5",
        "surface-container": "#efeded",
        "secondary": "#775a19",
        "on-secondary-fixed": "#261900",
        "on-primary-container": "#858383",
        "tertiary": "#000000",
        "surface": "#faf9f9",
        "primary-fixed-dim": "#c8c6c5",
        "secondary-fixed-dim": "#e9c176",
        "secondary-fixed": "#ffdea5",
        "primary-fixed": "#e5e2e1",
        "outline": "#747878",
        "on-secondary-fixed-variant": "#5d4201",
        "on-surface": "#1b1c1c",
        "on-error": "#ffffff",
        "surface-tint": "#5f5e5e",
        "tertiary-container": "#1b1c19",
        "background": "#faf9f9",
        "surface-container-high": "#e9e8e8",
        "surface-container-low": "#f4f3f3",
        "on-secondary-container": "#785a1a",
        "inverse-on-surface": "#f2f0f0",
        "on-tertiary-fixed-variant": "#474744",
        "on-primary-fixed": "#1c1b1b",
        "on-tertiary-fixed": "#1b1c19",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#dbdad9",
        "surface-bright": "#faf9f9",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#474746",
        "primary-container": "#1c1b1b",
        "on-surface-variant": "#444748",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#848480",
        "primary": "#000000",
        "outline-variant": "#c4c7c7",
        "tertiary-fixed-dim": "#c8c6c2",
        "surface-container-highest": "#e3e2e2",
        "on-background": "#1b1c1c",
        "error-container": "#ffdad6",
        "surface-variant": "#e3e2e2",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "inverse-surface": "#2f3031",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        sm: "16px",
        xs: "8px",
        lg: "32px",
        md: "24px",
        xxl: "64px",
        huge: "96px",
        xl: "48px",
      },
      fontFamily: {
        "display-xl": ["Noto Serif"],
        "headline-lg": ["Noto Serif"],
        "headline-md": ["Noto Serif"],
        "label-caps": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
      },
      fontSize: {
        "display-xl": ["72px", { "lineHeight": "80px", "letterSpacing": "-0.02em", "fontWeight": "400" }],
        "headline-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "headline-md": ["32px", { "lineHeight": "40px", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "32px", "letterSpacing": "0.01em", "fontWeight": "400" }],
      },
    },
  },
  plugins: [],
}

module.exports = config